steps:
    - name: gcr.io/kaniko-project/executor
      args:
          - >-
              --destination=$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
          - "--cache=true"
          - "-f"
          - Dockerfile
      #   secretEnv: ["DATABASE_URL"]
      id: Build
      timeout: 1200s
    - name: "gcr.io/cloud-builders/gcloud"
      args:
          - "run"
          - "deploy"
          - "knolyprod"
          - "--image"
          - "$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA"
          - "--region"
          - "us-central1"
          - "--platform"
          - "managed"
options:
    machineType: N1_HIGHCPU_8
    substitutionOption: ALLOW_LOOSE
substitutions:
    _GCR_HOSTNAME: us.gcr.io
    _PLATFORM: managed
    _SERVICE_NAME: knolyprod
tags:
    - gcp-cloud-build-deploy-cloud-run
    - gcp-cloud-build-deploy-cloud-run-managed
    - knolyprod
# availableSecrets:
#     secretManager:
#         - versionName: projects/$PROJECT_ID/secrets/KnolyProdDB/versions/latest
#           env: "DATABASE_URL"
