steps:
    - name: gcr.io/kaniko-project/executor
      args:
          - >-
              --destination=$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
          - "--cache=true"
          #   - --build-arg "databaseUrl=$DATABASE_URL"
          - "-f"
          - Dockerfile
      #   env:
      #     - name: DATABASE_URL
      #     - value: $DATABASE_URL
      #   secretEnv: ["DATABASE_URL"]
      id: Build
      timeout: 1200s
    - name: "gcr.io/cloud-builders/gcloud"
      args:
          - "run"
          - "deploy"
          - "knoilydev"
          - "--image"
          - "$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA"
          - "--region"
          - "us-central1"
          - "--platform"
          - "managed"
options:
    machineType: N1_HIGHCPU_8
    substitutionOption: ALLOW_LOOSE
substitutions:
    _DEPLOY_REGION: us-central1
    _GCR_HOSTNAME: us.gcr.io
    _PLATFORM: managed
    _SERVICE_NAME: knoilydev
    _LABELS: gcb-trigger-id=07dfad23-c76b-4ac4-b8b8-09320dab3aa2
    _TRIGGER_ID: 07dfad23-c76b-4ac4-b8b8-09320dab3aa2
tags:
    - gcp-cloud-build-deploy-cloud-run
    - gcp-cloud-build-deploy-cloud-run-managed
    - knoilydev
# availableSecrets:
#     secretManager:
#         - versionName: projects/$PROJECT_ID/secrets/KnolyDevDB/versions/latest
#           env: "DATABASE_URL"
