version: '3.1'

services:
  # app:
  #   build:
  #     context: ./
  #   ports:
  #     - "3000:3000"
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: devpasswd
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  redis:
    image: redis
    ports:
      - 6380:6379